import "./globals.css";
import type { Metadata } from "next";
<<<<<<< HEAD
import { Inter } from "next/font/google";
import { Providers } from "../provider";

const inter = Inter({ subsets: ["latin"] });

=======
import { Geist } from "next/font/google";

const geist = Geist({ subsets: ["latin"] });
import { Providers } from "../provider";
>>>>>>> main
export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
<<<<<<< HEAD
}): JSX.Element {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>{children}</body>
=======
}) {
  return (
    <html lang="en">
      <Providers>
              <body className={geist.className}>{children}</body>
>>>>>>> main
      </Providers>
    </html>
  );
}
